### ISSUE TITLE
Github considered harmful

### ISSUE THREAD

**Issue by mjog** [do-not-theme/do-not-theme.github.io#13]
Since Github is now [profiting](https://www.theverge.com/2019/10/9/20906213/github-ice-microsoft-software-email-contract-immigration-nonprofit-donation) from the mental and physical abuse of specific races of people in "detention" centres run by the US Government's ICE agency, I'm leaving organisations hosted on GitHub.

It would be good to move this org and repo to gitlab.com (it's a 1-click import to bring the repo over), if that happens I'll be happy join up there again.

**Comment by bertob** [comment]
Is there a way to migrate the repo and painlessly convert the Github Pages setup to Gitlab Pages, keep the custom domain, etc?

**Comment by markstos** [comment]
@mjog Is it still considered profiting when the contract is for $200,000 but, from the article: _"GitHub will donate $500,000 to nonprofits that support immigrant communities affected by Trump administration policies."_?  Is Gitlab donating $300,000 or more to related causes as well?

**Comment by mjog** [comment]
> @mjog Is it still considered profiting when the contract is for $200,000 but, from the article: _"GitHub will donate $500,000 to nonprofits that support immigrant communities affected by Trump administration policies."_? Is Gitlab donating $300,000 or more to related causes as well?

Yeah, I'm sure the couple of hot meals that $500,000 bought the people in detention *totally* made up for them being held in a jail, separated from their family.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I am not bothered by any financial support for American immigrative policy enough to consider negatively impacting my ability to contribute to code, but I am supportive of transferral to http://gitlab.com, because my experience of usage of it for public and private contribution, personal development of software, and duplication of data, has been immensely more positive than my experience of all of that via http://github.com. Consequently, please do consider http://github.com/do-not-theme/do-not-theme.github.io/issues/13.

**Comment by vayulove** [comment]
Being Microsoft should be reason enough for people to want to avoid it like the plague.  The ICE issue is just one example of countless profiteering horrors of MS and the resulting negative impact to variety and freedom within society it causes.

**Comment by davidak** [comment]
Since this open letter addresses "the wider GNOME community", i think it would make sense to move it to https://gitlab.gnome.org/World. I don't know if you have Pages setup there.

An independent non-profit git host i'm a member of is https://codeberg.org/. We have [Woodpecker CI](https://ci.codeberg.org/) und [Codeberg Pages](https://codeberg.page/).

There are many good reasons not to use GitHub, so i support this!

- GitHub itself is not Free Software
- GitHub is for-profit with millions of venture capital
- As any capitalists, they only care about profit; moral is only marketing
- GitHub bans users from certain countries due to US sanctions

There are good reasons to use GitHub:

- It is the monopolist; most developers have an account here
- It has a strong vendor lock-in with many proprietary tools like Actions

Since most of the criticism of GitHub also applies to Gitlab.com, i strongly suggest not to move there. It is not worth it!

**Comment by rokejulianlockhart** [comment]
@davidak, I agree with approximately all of https://github.com/do-not-theme/do-not-theme.github.io/issues/13#issuecomment-1262167593, except your conclusion: if GNOME has chosen GitLab, this should be hosted by http://gitlab.gnome.org.

**Comment by alatiera** [comment]
Gitlab is just as shit as Github, and we are not going to self host an instance fora single static website, this is just convenient.

There's no such thing as ethical consumption, and no point on wasting time on individual migrations.

**Comment by davidak** [comment]
>There's no such thing as ethical consumption

@alatiera Can you explain how you mean that? Why do you bother to contribute to GNOME when it would be **convenient** to use Microsoft Windows?

What is your perspective on how we can achieve positive change in society and economy? For me, it's providing better alternatives (like GNOME and Codeberg) for people to use, to make the now popular choices obsolete. But that only works when people care about better alternatives, we can't force them.

(I don't care about this specific issue.)
