### ISSUE TITLE
The solution

### ISSUE THREAD

**Issue by M-MAD-Official** [do-not-theme/do-not-theme.github.io#30]
> Though we could disable theming directly in our apps, we do not want to resort to this.

You said that you can make your apps unthemeable, then the problem is solved already!

All you need to do is to build two version of your apps; themeable and unthemeable; veteran Linux users and distribution packagers will get the themeable version, normies will get the unthemeable one which is guaranteed to work, look and feel the exact same way in every environment. In this way, you don't need to support the themeable version, because it's distribution packagers job, and if someone come to you and ask for support, you simply ask them to install the unthemeable version.

This is the easiest and most hassle-free solution; you need to change some of your app's source structure and add the option for enabling/disabling themeability in the build pipeline.

**Comment by bertob** [comment]
> In this way, you don't need to support the themeable version, because it's distribution packagers job

If that worked there would be no problem in the first place. If the app has the same name/brand, issues always end up upstream.

This doesn't solve anything unless downstreams fork and rebrand, which we know they don't have the manpower to do since they can't even keep up with packaging. Most new apps aren't distro packaged at all these days, and are basically Flathub-only...
