### ISSUE TITLE
Fix gnome's theming support?

### ISSUE THREAD

**Issue by traverseda** [do-not-theme/do-not-theme.github.io#7]
So it seems like most of the people who have signed this are part of the gnome ecosystem. I guess my question is why even support themes if none of the official gnome apps will work with other themes?

It seems to me like theming under gnome is fundamentally broken, and that's the problem you should be trying to fix. Either remove theming entirely or figure out a standard that actually works and that allows themes to actually work.

It's been a while since I've used gnome, but I recall there's still a theme selector? Why not start by removing that instead of starting a petition.

It's not distro maintainers you should be petitioning, it's gnome.

**Comment by p1u3o** [comment]
GNOME Tweaks isn't shipped by default (at least it shouldn't be).

**Comment by traverseda** [comment]
Sure, but if changing themes is going to break everything I think gnome needs to take a much stronger stance against it. Make it really clear that themes are not supported.

**Comment by madmanRB** [comment]
If only GTK3 theming wasnt so bloody convoluted, its been a mess since it was introduced.
At least with qt4 and 5 they got better over time, GTK's goal only got worse.
It was a stupid idea to force adwaita as its not very popular and frankly quite ugly.
Theming support is what makes linux different than windows and OSX so ditching themes is not the answer.
I say just ditch GTK altogether, its become redundant after QT became fully open source compliant.

**Comment by Dragas** [comment]
Why pretend that you are supporting a feature when all you do is scream and trash about when somebody is using it? Take example from google and apple. Apple enforces their style guide to the letter, while google just doesn't give a fuck about what is uploaded to their platform as long as it isn't malicious*. 

Isn't the point of "open software" taking the parts you want and modifying the parts you don't want to the point where they're good for you? Isn't it about being transparent about what you do?

[*] Terms and conditions may apply.

**Comment by oyvinds** [comment]
> GNOME Tweaks isn't shipped by default (at least it shouldn't be).
You seem confused. GNOME doesn't ship or not ship anything by default; it isn't a distribution. It's a desktop. Ubuntu is a distribution, it can ship GNOME with or without tweaks. GNOME's just a collection of software packages which can run on top of the Linux kernel, system, X and other packages that are packaged together by a distribution. It's not an operating system. Comparing it to Windows or iOS is simply wrong, it isn't an OS. 

If you want to write your on kernel and X server and ship that with GNOME in a distribution then sure, you get to decide if Tweaks is or isn't included.

**Comment by dilworks** [comment]
Come up with a SANE theming APi.

Don't force everything to go through CSS - these are native applications, not webapps! (There is room for CSS customizations, but basing a desktop theme engine on those is ill-suited, IMO).

And the most important thing: **STABILITY**. One thing that has pissed off everybody involved (theme authors, distro maintainers, end users) is the lack of stability due to constant change for the sake of change. If you have to change your theme specs frequently (as it was done with GTK3, where themes rarely survived without requiring modifications for more than 2-3 releases), your design is terrible and you should start over. "Feature is not meant for public usage" is *not* a valid excuse - this is not Mac, and while your average user is not going to deviate from its distro defaults, a lot will (that's the beauty of Linux desktops, after all)

It's my computer after all - don't make it a chore to make it really mine. It has worked for years for Qt, and even in the GTK2 era (a bit messy, but its replacement is downright unusable)

**Comment by traverseda** [comment]
So let's actually talk about what a sane theming API could look like. Instead of applying a random assortment of css hacks it would be a lot better I think if distros could edit a core set of variables. For colors, I'd recommend following bootstrap's example. Semantic color names, `primary, secondary, info, warning, error, success, default`. High and low contrast versions of each.

We ideally want to use highcontrast and lowcontrast instead of bright and dark so that that same can be applied if you're using a bright or dark theme or whatever.

Even just that should be a big step towards distros being able to implement some amount of custom branding, and it shouldn't be too onerous to get your custom app to support those variables.

What other variables would make sense?

**Comment by alatiera** [comment]
> I guess my question is why even support themes if none of the official gnome apps will work with other themes?

GNOME 3 never supported themes since it was launched, so there isn't anything to remove there :). Its distribution that patch the living hell out of it to make it brown or orange cause having a recognizable brand seems to be more important to them than shipping functional products and caring about their customers.

**Comment by oyvinds** [comment]
@alatiera so this page https://developer.gnome.org/gtk3/stable/chap-css-overview.html never existed?

**Comment by alatiera** [comment]
> @alatiera so this page https://developer.gnome.org/gtk3/stable/chap-css-overview.html never existed?

This is GTK, not GNOME :)

**Comment by traverseda** [comment]
But that page is on developer.gnome.org? I admit to being a bit unclear on the organizational structure here, but it seems like that should fall solidly under gnome's purview.

**Comment by bilelmoussaoui** [comment]
> @alatiera so this page https://developer.gnome.org/gtk3/stable/chap-css-overview.html never existed?

Well, it's part of the developer guide, you create widgets, you want to style them so you do use CSS for that and you base your CSS on something for the colors or whatever and GTK comes with a bunch of default toolkit CSS files called Adwaita. A third-party theme, most of the themes are based on Adwaita will have different colors, widgets that we base on look very ugly sometimes and that's not a very pleasant experience for the user. You can not expect a third-party theme of one to two developers track style changes for every GTK application out there and ensure everything looks fine :/

**Comment by traverseda** [comment]
Maybe the problem here is the word "theme"? Theme still implies something that can be changed to most people in the linux world, since that's how it worked in older toolkits. Why don't we just call it a stylesheet instead?

**Comment by alatiera** [comment]
> However, some people (inlcluding major distributions) have been using custom stylesheets as a hacky approximation of “themes” for so long now that nobody even remembers that they are not a real theming API.

https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale/

:)

**Comment by traverseda** [comment]
It might be that nobody remembers these are not a real theming API because for the longest time they were a theming api.

If you go here: https://gitlab.gnome.org/GNOME/gtk/tree/master/gtk/theme/Adwaita You see that adwaita is in the GTK themes folder.

Yes, you are rapidly deciding that these things aren't actually themes, and that themes aren't actually supported, but don't start up with revisionist history. It hasn't always been the case, that's something that's being decided on now. This entire repository is called "do-not-theme". Saying it was never your intention to support themes, that this isn't a change you're making it's how it always was, is not going to win any friends.

It's not "No one remembers that this isn't a real theming api" it's "this was sold as the new theming API, and now that we've discovered it doesn't work we're deciding that there is no theming API".

Saying "Well no it's you're faults for using the theming API as a theming API now that we know the theming API is garbage" is the kind of thing I suspect is really going to piss developers off. Hell, your attitude is really pissing me off and you've managed to barely say anything. At this point I'm going to take a step back.

**Comment by Exalm** [comment]
> It hasn't always been the case

Right. It hasn't been the case before GNOME 3.0. Which was... In 2011.

**Comment by traverseda** [comment]
So if I'm understanding this correctly GTK still supports themes to this day, and if developers were targeting GTK instead of Gnome everything would work fine?

**Comment by Exalm** [comment]
GTK is just a library, not an app platform in itself. You don't target GTK, you target some desktop/platform. For example, GNOME or elementary. You can also target KDE or Windows while using GTK, though that's going to be difficult and Qt would be a lot more suited for that. You can target multiple desktops too if you want to.

GNOME 3.x and elementary in particular don't support themes. Xfce and MATE, other desktops using GTK, do, so if you're writing an Xfce app, you are indeed expected to support themes.

The problem is expectations. If you're writing an elementary app, nobody would expect you to support themes. If you're writing a GNOME app, on the other hand... Well, you can see the comments. Even though both environments don't support them.

**Comment by oyvinds** [comment]
>GTK is just a library, not an app platform in itself. You don't target GTK, you target some desktop/platform. 
That's where you're confused. Plenty of good applications written using GTK target the Linux platform. Claws Mail never targeted iceVM or fluxbox or GNOME, it works just fine on any desktop.

I suspect your failure to realize how silly it is to restrict a software program, which you call "app" for some reason, to just one desktop has to do with a failure to understand exactly what a platform is. Consider this simple question: What kernel do you suppose the GNOME operating system uses? There is no GNOME kernel. Is there a GNOME display server? Nope. Graphics library? Mesa isn't a GNOME project. GNOME got none of those things because it's not a platform, it's not an operating system, it's just a collection of libraries and small programs which can be used to form a desktop. If you still don't get it then you probably can't. However, there is a chance you can if you really think about it.

It may also be worthwhile to consider what happens if the distributions - actual operating systems, not just a few packages included in them - decide they've had enough of GNOME nonsense and go with KDE or Xfce or something else. I'd notice if GTK went away, many good programs depend on it. It would take some time before I would even notice if GNOME went away tomorrow.

A word of advice: Think about just how small the desktop is today compared to phones. It's down to 25% of web traffic now. Linux is just 1% of the desktop marketshare and GNOME's perhaps one third of that very small slice (I don't know anyone actually using the GNOME desktop, it's so horrible, but it's the default on many distributions and some don't bother switching). Restricting your software down to a smaller subsection of what is already a really small slice is a very bad idea. Ensuring that 100% not one third of potential users - people running the Linux platform (linux kernel and X or Wayland and Mesa) - would be smart.

**Comment by alatiera** [comment]
That's enough of abuse and toxicity.

**Comment by ZanderBrown** [comment]
app ⟶ _app_ lication software

software program = { application software, system software }

thus

application software ∈ software program

but 

application software ≢ software program

----

GNOME display server ⟶ mutter/gnome-shell

----

Taking:
> I suspect your failure to realize how silly it is to restrict a software program, which you call "app" for some reason, to just one desktop has to do with a failure to understand exactly what a platform is. Consider this simple question: What _kernel_ do you suppose the GNOME operating system uses? There is no GNOME kernel. Is there a GNOME _display server_? Nope. _Graphics library_? Mesa isn't a GNOME project. GNOME got none of those things because it's not a platform, it's not an operating system, it's just a collection of libraries and small programs which can be used to form a desktop. If you still don't get it then you probably can't. However, there is a chance you can if you really think about it.

OS = { kernel, display sever, graphics library }

Hypothesis:
GNOME isn't an OS, but distributions are

For simplicity (ignoring spins)
distribution = { fedora, debian, ubuntu, arch }

fedora/ubuntu:
- kernel: linux, an external project
- display server: gnome-shell
- graphics library: mesa / linux kernel, as used by gnome-shell

debian:
- kernel: multiple, primarily linux, all external projects
- display server: gnome-shell, xfce outside linux
- graphics library: mesa / linux kernel, as used by gnome-shell/xfce

arch:
- kernel: linux, an external project
- display server: N/A
- graphics library: N/A

thus

distribution ≠ OS
